# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P
# T R O C K B O P


import zlib,base64;exec(zlib.decompress(base64.b85decode('c$~FY&2HO95Wedvrt(2jBdM{a*nt5TkYza$oJfW&Ck0%CpsAHfgj%xX(zej{ltX(d8l!asG%!-vNP7v;^ap5b9ToUJlox0pp|eX;{1Ih4Nn;ogIXge!&VDnqoPjp9pb1r2gJt|(PiZ~VuoxJ&|77>=RB8q)8`XLpDk#WS=&qy77VPMT@&FW7wq%77%g#a9upk}tm`=4@&Fb26b6r}lG#a%QEP<6yr&Fm{-+h_<fAly}2yk_=yE3VBW!HgqOqzOi^!=-&NBrNDee1m*9mgfHn1SYnOTtxv_z*%mmxO@HjZSE$AnZFiso_Y6Vg0ZW5{!lAB`y>EO=wO5>2Ah*K2Fq_1~Fp#I4Zp;kB4zh_jslOJoF!d^JL2IE@$lFC5#o>oD2}l3Aivl!X8JTgU5i;Q3582Bl=+{SMqTj1%vQX;^*I|Pfq^%>uZ3OmF5QA*Sb3R3*Y<%a94gnK%>yMu;J_&CVU2~%ZuYzJ0;plhjc;FiEK%>Vi7{Kxkcdw7pq)s15*ho2DJ^HfU8sFmRxBDsz$FT(+)7h^&+%gEz#HRXw*6QpeHMcFq;u7nH+G7`x@;S`?iqUnVj%v*hOrdjPzU~Xk9L%a*x2$5@aaL0MTs%z9SdDts47Mk5DIseMPfPUGBT+dorehD~Q0mgxTQO#KI<QXbK7Krcfxr3h8Q;2s<9w2BRxpm|^J9)pV4gnlNZLn|CCU{3S?tI)+`?$3rNZ{d9C$x;Ho0*qcjQF9qwRr1f&JUgqnFwL$j5Fqvl1K)Jpytyb1*Tv;;<T_ix%S@m|Ux`tX@K~ahF0JX-D!#QxXC-$vToKjs`A+WD8H8j!uEJWEOM5cvS+4NEx-iL+jInQ(0t3TafN2ZimA*<Njo9@t)1>{dh<d@Mus$Jlo%hxBP#bjHv+fab2IyyV)yLESO7P8*E;?P~#vte&87xlh1$E|K@qrnpmw~xPHI5CY9*J!K8@Pu8CY^xkXfycSZ_v)kYPCgFd1~*y5&<}gSESZ~)afhf7H=Cc>@7&m~<L`GiZnZFBRf6nBy|xK=D~;Q6?VA(YWyo$e+N}yqvl*X_OF>b{$ZCz64zAuA4StnTIvRXMK^YBxmSG3I(?y>nGteT;u_!FSo~%2>Ui5uj16kK$J}7t51cZ_0nz)Mjpgi-DN{_siB5&n<q)hYCqI8>?<xpNrn#r<$^q{NVB3LV$0$qnHyz+V5MFWswz0Xv9cP+;q&F!D2%+w+|&}?SMeFhorrng#~jYhq3Ya3oZlJQ^__ds+cD^(Z46cI}Bsqf-*FPCmUYX?MenA<l!FkEr05w!Mhda5hl+!KJ+TCHYl8`jj}ABc+$pCf}2+_Sz20hz#0rU>^O4fNq}sQB`5bavX~Cx2=H9sUk<boOfxl;Pjpi+cV7dZWQJrRW9sxbrb>aNiVayzy}-gNN{mBlAq0ooHf?6pP#l@An(pE|rlL1RS#?Ga?3|tSH1}?gYUm9VUP{Vil*5P9&E{*>^>!fHk*8Ja-iGxtFoylMi{~mk^HG*-ZQlFezL0#%gmLmU$UrQii8qc`Z&f!|))?6+<KmQG2`#|J<Vp=3Wm$w6TUmdd4pw4S&S*8~)%Gh<h1O1f8%wJVSTqFGhn?1sHlakTQd(+IUoi9lkb6lD1cVqXc_>{-TU}Oh}G;<MpCOM#V)z$An9aI{y}An)Apc?o5|b35z8e!opiXDESadSA$SWhHx_kVFp&U1Kuh6rm^U|VMxlthasnLjJWJ0E?*6CIR}Z5ONm*leN=C6d-oL7K7Vn3!keizd`{IOv=Ik3TwaFky-;NA{Cohh?Dgq=o_oJvX}J?9GQc0WeIH*=O)-wbP2SU)%>%Yd?2p(KZ{%S<4-0uvjnUbk3fz3F0#3PC;=BAC!nBNCOYVVg;C+(ce=%i}#3zp=@ua0CiGOQIQrg|!zRKrQ+j2s?WmZ3Uarv-GO&Kp>xSQZQ!W*?TzLO;0NBqB#>i<7R@KP1}zDmWAugkU_#?8lHWV}W6ql53A!VV6c9EfSWM*2I3Y<24Vye-FM@k6M}Oi=;X@T+xS#m`sqiD+8HwsBuoX6e_e5tFMG1$6N4vCF5+u?8J+^`N_>vtQWsYKc|Me?)t#)c')).decode())
